import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "LMS-Khan-Devs | Home",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="min-h-screen flex flex-col">
      <Navbar></Navbar>
        <main> {children}</main>
      </div>
    </ClerkProvider>
  );
}
